name: 'Build Matlab bindings'
description: 'Installs preCICE and builds the preCICE Matlab bindings in the directory. Ends in `$GITHUB_WORKSPACE/matlab-bindings`'

inputs:
  matlab-release:
    required: true
    default: 'latest'
    description: 'The release of Matlab to use.'
  precice-version:
    required: true
    default: '2.5.0'
    description: 'The version of preCICE to use.'

runs:
  using: "composite"
  steps:

    - name: Install precice # could break due to hard-coded link
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE
        wget https://github.com/precice/precice/releases/download/v${{ inputs.precice-version }}/libprecice2_${{ inputs.precice-version }}_focal.deb
        sudo apt install ./libprecice2_${{ inputs.precice-version }}_focal.deb

    - name: Set up Matlab
      uses: matlab-actions/setup-matlab@v1
      with: 
        release: ${{ inputs.matlab-release }}

    - name: Check out repository
      uses: actions/checkout@v3

    - name: Run compilation script
      uses: matlab-actions/run-command@v1
      with:
        command: compile_matlab_bindings_for_precice